In [5]:
import numpy as np 
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

In [24]:
# SVD
# define a matrix
A = array([[3,2,-2,-3], [2,4,-1,-5]])
m,n=np.shape(A)
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
s=np.array(s)
print(s)
print(U)
S = np.zeros((m, n))
S[:2, :2] = np.diag(s)
print(S)
print(VT)

[[ 3  2 -2 -3]
 [ 2  4 -1 -5]]
[8.28088129 1.85121718]
[[-0.58864133  0.80839433]
 [-0.80839433 -0.58864133]]
[[8.28088129 0.         0.         0.        ]
 [0.         1.85121718 0.         0.        ]]
[[-0.40849669 -0.53265586  0.23979054  0.70136202]
 [ 0.67409721 -0.39853598 -0.5553899   0.27982867]
 [ 0.57429598 -0.18920963  0.79244044 -0.0801374 ]
 [ 0.22115048  0.72225101  0.0779789   0.65066522]]


In [25]:
def s_cut(a,p):
    s1=np.zeros(len(a))
    for j in range(p):
        s1[j]=a[j]
    return s1

In [29]:
s_cut=s_cut(s,1)

In [30]:
S_cut = np.zeros((m, n))
S_cut[:2, :2] = np.diag(s_cut)
print(S_cut)
Ap = U.dot(S_cut.dot(VT))
print(Ap)

[[8.28088129 0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[ 1.99120445  2.59641446 -1.16885153 -3.41876737]
 [ 2.73456571  3.56571418 -1.60521001 -4.69506988]]
