In [105]:
import numpy as np
from numpy import linalg as la

In [106]:
#Solves the equation Ax=b via the Gauss-Seidel iterative method
# Create an initial guess if needed     
#Input:  square matrix A, row vector b, maximum number of steps N, initial guess x,
#        TOL1 stopping condition for solution to solve the system
#        TOL2 stopping condition or solutions to converge
#Output: solution x
def GaussSeidel(A, b,  N, x, TOL1, TOL2):
    n=len(A)
    x0=x
    x1=np.zeros(n)
    for j in range(N):
        for i in range(n):
            x1[i] = (b[i]-np.dot(A[i,i+1:n], x0[i+1:n]) - np.dot(A[i,0:i], x1[0:i])) / A[i,i]
        r    = b - np.dot(A,x1)
        if (la.norm(r) < TOL1) and (la.norm(x1-x0) < TOL2):
            print('Approximate solution', x1, 'in steps=', j)
            return(x1)    
        x0=x1    
    return x1

In [107]:
A = np.array([[3, 1, -1], [2, 4, 1], [-1, 2, 5]])
b = np.array([4, 1, 1])
x = np.array([1, 0, 0])
TOL1=1.e-6
TOL2=1.e-6
N=25
GaussSeidel(A, b, N, x,TOL1,TOL2)

Approximate solution [ 1.99999975 -0.9999998   0.99999987] in steps= 18


array([ 1.99999975, -0.9999998 ,  0.99999987])

In [108]:
def tridiag(d1, d2, d3, k1=-1, k2=0, k3=1):
    return np.diag(d1, k1) + np.diag(d2, k2) + np.diag(d3, k3)
d1 = (-1)*np.ones(9); d2 = 3*np.ones(10); d3 = (-1)*np.ones(9)
A2=tridiag(d1, d2, d3)
b2=np.array([2.5,1.5,2.5,1.5,1.0,1.0,1.5,2.5,1.5,2.5])
print(A2)
print(b2)
x2 = 1*np.ones(10)
TOL1=1.e-6
TOL2=1.e-6
N=50
GaussSeidel(A2, b2, N, x2,TOL1,TOL2)

[[ 3. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  3. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  3. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  3. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  3. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  3. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  3. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  3. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  3. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  3.]]
[2.5 1.5 2.5 1.5 1.  1.  1.5 2.5 1.5 2.5]
Approximate solution [1.35955025 1.5786513  1.87640414 1.55056152 1.27528071 1.27528077
 1.55056172 1.87640446 1.57865167 1.35955056] in steps= 17


array([1.35955025, 1.5786513 , 1.87640414, 1.55056152, 1.27528071,
       1.27528077, 1.55056172, 1.87640446, 1.57865167, 1.35955056])