In [62]:
import numpy as np

In [63]:
#Function to solve a square system of equations
#Input: n x n matrix a, n-row vector b, eps parameter for zero pivot 
#Output: solution x
def Gaussian(a,b):
    eps=1.e-30
    nrow=len(a)
    ncol=len(a[0])
    n=len(b)
    if nrow != ncol:
        print('Not square matrix')
        return None
    if ncol != n: 
        print('System not solvable')
        return None
    x=np.zeros(n)
    #Print initial augumented matrix
    print(np.column_stack((a, b)))
    for k in range(0,n-1):
        if np.abs(a[k,k])<eps:
            print('Zero pivot')
            return None 
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                mult = a[i,k]/a[k,k]
                a[i,k:n] = a[i,k:n] - mult*a[k,k:n]
                #The alternative computation below eliminates one unnecessary step
                #a[i,k+1:n] = a[i,k+1:n] - mult*a[k,k+1:n]
                b[i] = b[i] - mult*b[k]
                #Print augumented matrix at each step of elimination
                print(np.column_stack((a, b)))
    # Back substitution
    for k in range(n-1,-1,-1):
        b[k] = b[k] - np.dot(a[k,k+1:n],x[k+1:n])
        x[k]=b[k]/a[k,k]
    return x

In [64]:
A=np.array([[1,2,1],[3,2,4],[4,4,3]])
b=np.array([5,17,26]).T
Gaussian(A,b)

[[ 1  2  1  5]
 [ 3  2  4 17]
 [ 4  4  3 26]]
[[ 1  2  1  5]
 [ 0 -4  1  2]
 [ 4  4  3 26]]
[[ 1  2  1  5]
 [ 0 -4  1  2]
 [ 0 -4 -1  6]]
[[ 1  2  1  5]
 [ 0 -4  1  2]
 [ 0  0 -2  4]]


array([ 9., -1., -2.])

In [65]:
A1=np.array([[0,2,1],[3,8,1],[0,4,1]])
b1=np.array([5,17,26]).T
Gaussian(A1,b1)

[[ 0  2  1  5]
 [ 3  8  1 17]
 [ 0  4  1 26]]
Zero pivot


In [66]:
A2=np.random.rand(10,10)
b2=np.random.rand(10)
Gaussian(A2,b2)

[[0.10587721 0.32251127 0.11903752 0.17480674 0.41153449 0.29151088
  0.0908001  0.66979762 0.45527109 0.62325266 0.30994226]
 [0.16854114 0.95061595 0.24179298 0.04674614 0.74307728 0.01139416
  0.61912267 0.81114192 0.00243898 0.29398013 0.06568381]
 [0.47485323 0.9269588  0.30575774 0.72443914 0.34599107 0.80181543
  0.67668185 0.61045609 0.02069623 0.58386414 0.58549082]
 [0.28546607 0.82806186 0.3142842  0.4051915  0.08532678 0.01179046
  0.06621117 0.13768916 0.84024264 0.8484021  0.48132839]
 [0.35631459 0.25421266 0.7759552  0.29232146 0.27308712 0.93545414
  0.67540396 0.39569328 0.36266701 0.05364396 0.52066831]
 [0.03838362 0.62513474 0.28254273 0.66515124 0.5263299  0.14118943
  0.07517319 0.49610533 0.16497444 0.17224629 0.72722471]
 [0.48828282 0.37909043 0.71864816 0.28219384 0.06898021 0.09172916
  0.03928307 0.46154168 0.01428414 0.18262102 0.08696165]
 [0.82528907 0.11295802 0.71552187 0.15229771 0.03789998 0.1105699
  0.63595364 0.99250741 0.72115328 0.29476144 0.586

array([-0.20802192,  0.75562794, -0.59566686,  0.64615303, -0.78569486,
        0.53602615, -0.37243767,  0.82913169,  1.0484512 , -1.2604137 ])

In [67]:
A3=np.array([[1e-20,1],[1,2]], dtype='long')
b3=np.array([1,4]).T
Gaussian(A3,b3)

[[0 1 1]
 [1 2 4]]
Zero pivot


In [68]:
A4=np.array([[1,2],[1e-20,1]], dtype='long')
b4=np.array([4,1]).T
Gaussian(A4,b4)

[[1 2 4]
 [0 1 1]]


array([2., 1.])