In [23]:
import numpy as np

In [24]:
# QR factorization using Numpy
# Original matrix A
A = np.array([[2, 1], [1, -1], [2, 1]]) 
print(A) 
# Decomposition of the matrix 
# Options: reduced or complete
Q, R = np.linalg.qr(A, mode='complete') 

print('\nQ:\n', Q) 
print('\nR:\n', R) 

[[ 2  1]
 [ 1 -1]
 [ 2  1]]

Q:
 [[-6.66666667e-01  2.35702260e-01 -7.07106781e-01]
 [-3.33333333e-01 -9.42809042e-01 -2.13241722e-16]
 [-6.66666667e-01  2.35702260e-01  7.07106781e-01]]

R:
 [[-3.         -1.        ]
 [ 0.          1.41421356]
 [ 0.          0.        ]]
