In [1]:
import numpy as np

In [2]:
# Power iteration to find dominant eigenvalue and eigenvector
# Input:  A=matrix, x0=initial vector, k=number of steps
# Output: lambda_max=dominant eigenvalue, v_max=dominant eigenvector
def powerit(A,x0,k):
    x=x0
    for j in range(k):
        u=((np.dot(x,x))**(-0.5))*x #u is a unit vector
        x=A.dot(u)
        lambda_j=u.dot(x) #Rayleigh quotient
    lambda_max=lambda_j
    v_max=(np.dot(x,x)**(-0.5))*x
    return lambda_max, v_max

In [3]:
A=np.array([[1,3],[2,2]])
x0=np.array([-5,5])
k=20
lambda_max,v_max=powerit(A,x0,k)
print(lambda_max,v_max)

3.99999999998181 [0.70710678 0.70710678]


In [13]:
# Matrix whose characteristic polynomial is the Wilkinson polynomial
w=np.array(range(1,21))
W=np.diag(w)
print(W)
y0=np.ones(20)
k=500
lambda_max,v_max=powerit(W,y0,k)
print(lambda_max,v_max)

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0