In [187]:
import numpy as np 

In [188]:
# QR algorithm for eigenvalues and eigenvectors of symmetric matrix 
# Input: A=matrix, k=number of steps
# Output: Evec=orthogonal eigenvectors and Eval=eigenvalues
def QRsym(A,k):
    if np.any(A.T!=A):
        print('Not a symmetric matrix')
        return None
    else:
        [m,n]=np.shape(A)
        Q=np.eye(m)
        Qbar=Q
        for j in range(k):
            Qbar,R=np.linalg.qr(np.dot(A,Qbar))
        Evec=Qbar;Eval=np.diag(R) 
    return Evec, Eval

In [189]:
A=np.array([[3,2,4],[2,0,2],[4,2,3]])
print(A)

[[3 2 4]
 [2 0 2]
 [4 2 3]]


In [190]:
QRsym(A,10)

(array([[-6.66666667e-01,  4.47213595e-01, -5.96284793e-01],
        [-3.33333333e-01, -8.94427191e-01, -2.98142397e-01],
        [-6.66666666e-01, -4.16499563e-10,  7.45355993e-01]]),
 array([ 8., -1., -1.]))

In [191]:
np.linalg.eig(A)

(array([-1.,  8., -1.]),
 array([[-0.74535599,  0.66666667, -0.20756326],
        [ 0.2981424 ,  0.33333333, -0.77602137],
        [ 0.59628479,  0.66666667,  0.59557394]]))

In [192]:
#Failure of convergence
A1=np.array([[0,1],[1,0]])
print("A1=",A1)
Evec, Eval=QRsym(A1,10)
print(Evec,Eval)
print(np.linalg.eig(A1))

A1= [[0 1]
 [1 0]]
[[ 1.  0.]
 [-0.  1.]] [-1. -1.]
(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [193]:
# Unshifted QR algorithm for eigenvalues and eigenvectors of symmetric matrix 
# Input: A=matrix, k=number of steps
# Output: Evec=orthogonal eigenvectors and Eval=eigenvalues
def QRunshifted(A,k):
    if np.any(A.T!=A):
        print('Not a symmetric matrix')
        return None
    else:
        [m,n]=np.shape(A)
        Q=np.eye(m)
        Qbar=Q;R=A
        for j in range(k):
            Q,R=np.linalg.qr(np.dot(R,Q))
            Qbar=np.dot(Qbar,Q)
        RQ=np.dot(R,Q)
        Eval=np.diag(RQ) 
    return Eval

In [186]:
QRunshifted(A,10)

array([ 8., -1., -1.])