In [9]:
import numpy as np 
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

In [12]:
# Reconstruct SVD
# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1,1,1]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
print('Singular values=',s)
m,n=np.shape(A)
k=min(m,n)
S = np.zeros((m, n))
S[:k, :k] = np.diag(s)
print('U=',U)
print('S=',S)
print('VT=',VT)
# reconstruct matrix
B = U.dot(S.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]]
Singular values= [1.69353938e+01 1.09198772e+00 4.31563540e-17]
U= [[-0.2136533  -0.87256508 -0.43709456  0.04394086]
 [-0.51788213 -0.2552086   0.78514026  0.22410139]
 [-0.82211097  0.36214788 -0.3480457  -0.26804225]
 [-0.10140961  0.20578549 -0.26714659  0.93594932]]
S= [[1.69353938e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.09198772e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.31563540e-17]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
VT= [[-0.48073097 -0.57247058 -0.66421019]
 [ 0.77603548  0.07490508 -0.62622533]
 [-0.40824829  0.81649658 -0.40824829]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 1. 1.]]
